"""create_user_persona_table

Revision ID: 05a5c0b7f56a
Revises: f1eff34f6149
Create Date: 2025-06-26 13:32:16.740004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05a5c0b7f56a'
down_revision: Union[str, None] = 'f1eff34f6149'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_personas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('persona_data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_personas_id'), 'user_personas', ['id'], unique=False)
    op.create_index(op.f('ix_user_personas_user_id'), 'user_personas', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_personas_user_id'), table_name='user_personas')
    op.drop_index(op.f('ix_user_personas_id'), table_name='user_personas')
    op.drop_table('user_personas')
    # ### end Alembic commands ###
