"""Add responds_to link to messages

Revision ID: 1cc4aa6ef702
Revises: cbb2bc2cd5ac
Create Date: 2025-04-30 23:37:15.505490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1cc4aa6ef702'
down_revision: Union[str, None] = 'cbb2bc2cd5ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('responds_to_message_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'messages', 'messages', ['responds_to_message_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_column('messages', 'responds_to_message_id')
    # ### end Alembic commands ###
