"""add_prompt_version_id_to_conversations

Revision ID: 36a75af4bf63
Revises: 60f235efa672
Create Date: 2025-05-21 01:28:37.234056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36a75af4bf63'
down_revision: Union[str, None] = '60f235efa672'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('prompt_version_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'conversations', 'prompt_versions', ['prompt_version_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.drop_column('conversations', 'prompt_version_id')
    # ### end Alembic commands ###
