"""add_students_tags

Revision ID: 59691f10bab7
Revises: 1f9d9bb0c7a8
Create Date: 2026-01-19 02:23:00.972905

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '59691f10bab7'
down_revision: Union[str, None] = '1f9d9bb0c7a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tags_id'), 'tags', ['id'], unique=False)
    op.create_index(op.f('ix_tags_name'), 'tags', ['name'], unique=True)
    op.create_table('student_tags',
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('student_id', 'tag_id')
    )
    op.drop_index('ix_analysis_jobs_status', table_name='analysis_jobs')
    op.drop_constraint('uq_analysis_jobs_job_id', 'analysis_jobs', type_='unique')
    op.create_index(op.f('ix_analysis_jobs_id'), 'analysis_jobs', ['id'], unique=False)
    op.create_index(op.f('ix_analysis_jobs_job_id'), 'analysis_jobs', ['job_id'], unique=True)
    op.create_index(op.f('ix_class_analyses_id'), 'class_analyses', ['id'], unique=False)
    op.alter_column('class_daily_metrics', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_class_daily_metrics_id'), 'class_daily_metrics', ['id'], unique=False)
    op.alter_column('class_summary_metrics', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_class_summary_metrics_id'), 'class_summary_metrics', ['id'], unique=False)
    op.drop_index('ix_conversation_evaluations_status', table_name='conversation_evaluations')
    op.drop_constraint('uq_conversation_evaluations_conversation', 'conversation_evaluations', type_='unique')
    op.drop_index('ix_conversation_evaluations_conversation_id', table_name='conversation_evaluations')
    op.create_index(op.f('ix_conversation_evaluations_conversation_id'), 'conversation_evaluations', ['conversation_id'], unique=True)
    op.create_index(op.f('ix_conversation_evaluations_id'), 'conversation_evaluations', ['id'], unique=False)
    op.alter_column('hourly_activity_metrics', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_hourly_activity_metrics_id'), 'hourly_activity_metrics', ['id'], unique=False)
    op.drop_constraint('uq_student_analysis_student_id', 'student_analyses', type_='unique')
    op.drop_index('ix_student_analyses_student_id', table_name='student_analyses')
    op.create_index(op.f('ix_student_analyses_student_id'), 'student_analyses', ['student_id'], unique=True)
    op.create_index(op.f('ix_student_analyses_id'), 'student_analyses', ['id'], unique=False)
    op.alter_column('student_daily_metrics', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_student_daily_metrics_id'), 'student_daily_metrics', ['id'], unique=False)
    op.alter_column('student_summary_metrics', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_student_summary_metrics_id'), 'student_summary_metrics', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_student_summary_metrics_id'), table_name='student_summary_metrics')
    op.alter_column('student_summary_metrics', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_student_daily_metrics_id'), table_name='student_daily_metrics')
    op.alter_column('student_daily_metrics', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_student_analyses_id'), table_name='student_analyses')
    op.drop_index(op.f('ix_student_analyses_student_id'), table_name='student_analyses')
    op.create_index('ix_student_analyses_student_id', 'student_analyses', ['student_id'], unique=False)
    op.create_unique_constraint('uq_student_analysis_student_id', 'student_analyses', ['student_id'])
    op.drop_index(op.f('ix_hourly_activity_metrics_id'), table_name='hourly_activity_metrics')
    op.alter_column('hourly_activity_metrics', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_conversation_evaluations_id'), table_name='conversation_evaluations')
    op.drop_index(op.f('ix_conversation_evaluations_conversation_id'), table_name='conversation_evaluations')
    op.create_index('ix_conversation_evaluations_conversation_id', 'conversation_evaluations', ['conversation_id'], unique=False)
    op.create_unique_constraint('uq_conversation_evaluations_conversation', 'conversation_evaluations', ['conversation_id'])
    op.create_index('ix_conversation_evaluations_status', 'conversation_evaluations', ['status'], unique=False)
    op.drop_index(op.f('ix_class_summary_metrics_id'), table_name='class_summary_metrics')
    op.alter_column('class_summary_metrics', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_class_daily_metrics_id'), table_name='class_daily_metrics')
    op.alter_column('class_daily_metrics', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_class_analyses_id'), table_name='class_analyses')
    op.drop_index(op.f('ix_analysis_jobs_job_id'), table_name='analysis_jobs')
    op.drop_index(op.f('ix_analysis_jobs_id'), table_name='analysis_jobs')
    op.create_unique_constraint('uq_analysis_jobs_job_id', 'analysis_jobs', ['job_id'])
    op.create_index('ix_analysis_jobs_status', 'analysis_jobs', ['status'], unique=False)
    op.drop_table('student_tags')
    op.drop_index(op.f('ix_tags_name'), table_name='tags')
    op.drop_index(op.f('ix_tags_id'), table_name='tags')
    op.drop_table('tags')
    # ### end Alembic commands ###
