"""add lm_homework

Revision ID: 62d81c693dec
Revises: 97e161350341
Create Date: 2025-10-30 11:08:29.006961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62d81c693dec'
down_revision: Union[str, None] = '97e161350341'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lm_homework',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('conversation_id_generated', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='Active', nullable=False),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('response_of_kid', sa.Text(), nullable=True),
    sa.Column('conversation_id_discussed', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("status IN ('Complete','Incomplete','Active')", name='ck_lm_homework_status_valid'),
    sa.ForeignKeyConstraint(['conversation_id_discussed'], ['conversations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['conversation_id_generated'], ['conversations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lm_homework_conversation_id_discussed'), 'lm_homework', ['conversation_id_discussed'], unique=False)
    op.create_index(op.f('ix_lm_homework_conversation_id_generated'), 'lm_homework', ['conversation_id_generated'], unique=False)
    op.create_index(op.f('ix_lm_homework_id'), 'lm_homework', ['id'], unique=False)
    op.create_index(op.f('ix_lm_homework_status'), 'lm_homework', ['status'], unique=False)
    op.create_index(op.f('ix_lm_homework_user_id'), 'lm_homework', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lm_homework_user_id'), table_name='lm_homework')
    op.drop_index(op.f('ix_lm_homework_status'), table_name='lm_homework')
    op.drop_index(op.f('ix_lm_homework_id'), table_name='lm_homework')
    op.drop_index(op.f('ix_lm_homework_conversation_id_generated'), table_name='lm_homework')
    op.drop_index(op.f('ix_lm_homework_conversation_id_discussed'), table_name='lm_homework')
    op.drop_table('lm_homework')
    # ### end Alembic commands ###
