"""add_prompt_version_to_conv

Revision ID: 775538e70d75
Revises: d512e477df5c
Create Date: 2025-05-21 00:04:57.169071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '775538e70d75'
down_revision: Union[str, None] = 'd512e477df5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_unique_active_prompt_version', table_name='prompt_versions', postgresql_where='(is_active = true)')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_unique_active_prompt_version', 'prompt_versions', ['prompt_id'], unique=True, postgresql_where='(is_active = true)')
    # ### end Alembic commands ###
