"""add_core_chat_theme_to_conversations

Revision ID: 97e161350341
Revises: 38ce817ba776
Create Date: 2025-10-23 13:59:40.366436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97e161350341'
down_revision: Union[str, None] = '38ce817ba776'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_conversation_visits_conversation_id', table_name='conversation_visits')
    op.drop_index('idx_conversation_visits_visit_number', table_name='conversation_visits')
    op.create_index(op.f('ix_conversation_visits_conversation_id'), 'conversation_visits', ['conversation_id'], unique=True)
    op.create_index(op.f('ix_conversation_visits_id'), 'conversation_visits', ['id'], unique=False)
    op.create_index(op.f('ix_conversation_visits_user_id'), 'conversation_visits', ['user_id'], unique=False)
    op.create_index(op.f('ix_conversation_visits_visit_number'), 'conversation_visits', ['visit_number'], unique=False)
    op.add_column('conversations', sa.Column('core_chat_theme', sa.String(), nullable=True))
    op.drop_index('idx_prompts_purpose', table_name='prompts')
    op.create_index(op.f('ix_prompts_prompt_purpose'), 'prompts', ['prompt_purpose'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prompts_prompt_purpose'), table_name='prompts')
    op.create_index('idx_prompts_purpose', 'prompts', ['prompt_purpose'], unique=False)
    op.drop_column('conversations', 'core_chat_theme')
    op.drop_index(op.f('ix_conversation_visits_visit_number'), table_name='conversation_visits')
    op.drop_index(op.f('ix_conversation_visits_user_id'), table_name='conversation_visits')
    op.drop_index(op.f('ix_conversation_visits_id'), table_name='conversation_visits')
    op.drop_index(op.f('ix_conversation_visits_conversation_id'), table_name='conversation_visits')
    op.create_index('idx_conversation_visits_visit_number', 'conversation_visits', ['visit_number'], unique=False)
    op.create_index('idx_conversation_visits_conversation_id', 'conversation_visits', ['conversation_id'], unique=False)
    # ### end Alembic commands ###
