"""add lm_user_knowledge

Revision ID: d0042b026319
Revises: 62d81c693dec
Create Date: 2025-10-31 13:45:41.133685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0042b026319'
down_revision: Union[str, None] = '62d81c693dec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lm_user_knowledge',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('conversation_id', sa.Integer(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'conversation_id', name='uq_user_conversation')
    )
    op.create_index(op.f('ix_lm_user_knowledge_conversation_id'), 'lm_user_knowledge', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_lm_user_knowledge_id'), 'lm_user_knowledge', ['id'], unique=False)
    op.create_index(op.f('ix_lm_user_knowledge_user_id'), 'lm_user_knowledge', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lm_user_knowledge_user_id'), table_name='lm_user_knowledge')
    op.drop_index(op.f('ix_lm_user_knowledge_id'), table_name='lm_user_knowledge')
    op.drop_index(op.f('ix_lm_user_knowledge_conversation_id'), table_name='lm_user_knowledge')
    op.drop_table('lm_user_knowledge')
    # ### end Alembic commands ###
