"""ondelete set to null

Revision ID: eea6b4548bb3
Revises: 22b3966adbac
Create Date: 2025-06-11 20:20:34.515542

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eea6b4548bb3'
down_revision: Union[str, None] = '22b3966adbac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('conversations_prompt_version_id_fkey', 'conversations', type_='foreignkey')
    op.create_foreign_key(None, 'conversations', 'prompt_versions', ['prompt_version_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint('messages_responds_to_message_id_fkey', 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'messages', ['responds_to_message_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key('messages_responds_to_message_id_fkey', 'messages', 'messages', ['responds_to_message_id'], ['id'])
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.create_foreign_key('conversations_prompt_version_id_fkey', 'conversations', 'prompt_versions', ['prompt_version_id'], ['id'])
    # ### end Alembic commands ###
