"""data migration for user feedback table

Revision ID: f6146a303440
Revises: ed44f3d78370
Create Date: 2024-08-01 13:02:18.106674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6146a303440'
down_revision: Union[str, None] = 'ed44f3d78370'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('TRUNCATE TABLE user_feedback RESTART IDENTITY CASCADE;')
    op.add_column('user_feedback', sa.Column('feedback_data', sa.JSON(), nullable=False))
    op.drop_index('ix_user_feedback_id', table_name='user_feedback')
    op.drop_column('user_feedback', 'thumbs_up')
    op.drop_column('user_feedback', 'feedback_text')
    op.create_index(op.f('ix_user_feedback_id'), 'user_feedback', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_feedback_id'), table_name='user_feedback')
    op.add_column('user_feedback', sa.Column('feedback_text', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('user_feedback', sa.Column('thumbs_up', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.create_index('ix_user_feedback_id', 'user_feedback', ['id'], unique=False)
    op.drop_column('user_feedback', 'feedback_data')
    # ### end Alembic commands ###
