name: Deploy Frontend to AWS S3 and CloudFront

on:
  push:
    branches:
      - release
    paths:
      - 'curiosity-coach-frontend/**'
      - '.github/workflows/deploy-frontend.yml'
  workflow_dispatch: # Allows manual triggering

permissions:
  contents: read # Required to check out the code

jobs:
  deploy:
    name: Build and Deploy Frontend
    runs-on: ubuntu-latest
    # Optional: Specify the environment if you use GitHub Environments
    # environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Specify your Node.js version
          # Cache is now directory-specific
          # cache: 'npm' 

      - name: Configure AWS Credentials with Access Keys
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Install Dependencies
        working-directory: ./curiosity-coach-frontend
        run: |
          npm ci # Faster and more reliable than 'npm install' for CI

      - name: Get Backend API Gateway URL
        id: get_backend_url
        run: |
          API_NAME="curiosity-coach-backend-dev-api"
          API_URL=$(aws apigatewayv2 get-apis --region ap-south-1 --query "Items[?Name=='$API_NAME'].ApiEndpoint" --output text)
          if [ -z "$API_URL" ]; then
            echo "Error: Could not find API Gateway with name $API_NAME"
            exit 1
          fi
          echo "Found Backend API URL: $API_URL"
          echo "FUNCTION_URL=$API_URL" >> $GITHUB_ENV

      - name: Get Brain API Gateway URL
        id: get_brain_url
        run: |
          API_NAME="curiosity-coach-brain-lambda-api"
          API_URL=$(aws apigatewayv2 get-apis --region ap-south-1 --query "Items[?Name=='$API_NAME'].ApiEndpoint" --output text)
          if [ -z "$API_URL" ]; then
            echo "Error: Could not find API Gateway with name $API_NAME"
            exit 1
          fi
          echo "Found Brain API URL: $API_URL"
          echo "BRAIN_FUNCTION_URL=$API_URL" >> $GITHUB_ENV

      - name: Build Frontend Application
        working-directory: ./curiosity-coach-frontend
        run: npm run build
        env:
          # Use the dynamically fetched Lambda URL
          REACT_APP_BACKEND_BASE_URL: ${{ env.FUNCTION_URL }}
          REACT_APP_BRAIN_API_URL: ${{ env.BRAIN_FUNCTION_URL }}

      - name: Deploy to S3 Bucket
        run: |
          aws s3 sync ./curiosity-coach-frontend/build s3://${{ secrets.AWS_S3_BUCKET_NAME }} --delete

      - name: Invalidate CloudFront Cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id E1PWT352WPN7AO \
            --paths "/*" # Invalidate everything 